name: pass_the_dice
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <=3.0.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_data: 1.5.12
  hooks_riverpod: ^2.3.7 
  flutter_hooks: ^0.20.0
  fl_chart: ^0.63.0
  path_provider: ^2.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1 
  fast_immutable_collections: ^9.1.5  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.4
  custom_lint: ^0.4.0
  riverpod_lint: ^1.4.0
  freezed: ^2.4.1 
  json_serializable: ^6.7.1 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true